module_name = "Freehold Trash"

[npcs]
sharkbait = 129743
irontide_enforcer = 129602
irontide_bonesaw = 129788
irontide_crackshot = 126918
irontide_corsair = 126928
cutwater_duelist = 129559
irontide_oarsman = 127111
cutwater_knife_juggler = 129599
bilge_rat_brinescale = 129600
blacktooth_scrapper = 129529
blacktooth_knuckleduster = 129547
bilge_rat_swabby = 129526
vermin_trapper = 130404
bilge_rat_buccaneer = 129527
bilge_rat_padfoot = 129550
soggy_shiprat = 130024
irontide_crusher = 130400
irontide_buccaneer = 130011
irontide_ravager = 130012
irontide_officer = 127106
irontide_stormcaller = 126919
