module_name = "Horrific Vision of Stormwind Trash"

[npcs]
crawling_corruption = 160061
fallen_heartpiercer = 158092
enthralled_footman = 153760
fallen_riftwalker = 158146
cultist_slavedriver = 157158
inquisitor_darkspeak = 158136
fallen_taskmaster = 158437
forge_guard_hurrul = 158158
fallen_voidspeaker = 152722
si7_informant = 156795
alxkov_the_infested = 152809
armsmaster_terenson = 156949
greater_void_elemental = 153130
boundless_corruption = 152939
portal_keeper = 159275
zardeth_of_the_black_claw = 158371
