module_name = "Horrific Vision of Stormwind Trash"

[npcs]
crawling_corruption = 160061
enthralled_footman = 153760
fallen_voidspeaker = 152722
void_globule = 152669
fallen_heartpiercer = 158092
fallen_riftwalker = 158146
cultist_slavedriver = 157158
cultist_tormenter = 158690
inquisitor_darkspeak = 158136
fallen_taskmaster = 158437
faceless_willbreaker = 152987
enthralled_weaponsmith = 156641
forge_guard_hurrul = 158158
si7_informant = 156795
armsmaster_terenson = 156949
burrowing_appendage = 156145
dod = 156820
alxkov_the_infested = 152809
greater_void_elemental = 153130
boundless_corruption = 152939
portal_keeper = 159275
zardeth_of_the_black_claw = 158371
unstable_servant = 158411
