module_name = "The MOTHERLODE!! Trash"

[npcs]
refreshment_vendor = 136470
mech_jockey = 130488
mechanized_peacekeeper = 136139
addled_thug = 130435
hired_assassin = 134232
azerite_extractor = 136643
venture_co_earthshaper = 130661
wanton_sapper = 130653
stonefury = 130635
taskmaster_askari = 134012
weapons_tester = 136934
venture_co_mastermind = 133430
venture_co_alchemist = 133432
venture_co_war_machine = 133463
ordnance_specialist = 137029
