module_name = "Tazavesh Trash"

[npcs]
gatewarden_zomazz = 178392
customs_security = 177807
interrogation_specialist = 177816
portalmancer_zohonn = 179334
armored_overseer = 177808
support_officer = 177817
tracker_zokorss = 179837
ancient_core_hound = 180091
enraged_direhorn = 180495
cartel_skulker = 179893
cartel_wiseguy = 180336
cartel_muscle = 180348
cartel_smuggler = 180335
defective_sorter = 176396
overloaded_mailemental = 176395
post_worker = 176394
bazaar_overseer = 246285
market_peacekeeper = 179840
veteran_sparkcaster = 179841
commerce_enforcer = 179842
commander_zofar = 179821
murkbrine_scalebinder = 178141
murkbrine_fishmancer = 178142
murkbrine_shellcrusher = 178139
coastwalker_goliath = 178165
stormforged_guardian = 178171
burly_deckhand = 180015
hourglass_tidesage = 179388
corsair_officer = 179386
adorned_starseer = 180429
focused_ritualist = 180431
devoted_accomplice = 180432
