module_name = "Grim Batol Trash"

[npcs]
twilight_earthcaller = 224219
twilight_brute = 224152
twilight_destroyer = 224609
twilight_overseer = 224221
twilight_beguiler = 40167
molten_giant = 40166
twilight_warlock = 224271
twilight_flamerender = 224240
twilight_lavabender = 224249
faceless_corruptor = 39392
