module_name = "The Vortex Pinnacle Trash"

[npcs]
armored_mistral = 45915
gust_soldier = 45477
wild_vortex = 45912
lurking_tempest = 45704
cloud_prince = 45917
turbulent_squall = 45924
empyrean_assassin = 45922
young_storm_dragon = 45919
executor_of_the_caliph = 45928
temple_adept = 45935
servant_of_asaad = 45926
minister_of_air = 45930
