module_name = "Cinderbrew Meadery Trash"

[npcs]
venture_co_pyromaniac = 218671
hired_muscle = 210269
tasting_room_attendant = 214920
chef_chewie = 214697
cooking_pot = 219415
flamethrower = 219667
flavor_scientist = 222964
careless_hopgoblin = 223423
brew_drop = 223562
taste_tester = 220060
bee_wrangler = 210264
venture_co_honey_harvester = 220946
royal_jelly_purveyor = 220141
yes_man = 219588
