module_name = "Darkflame Cleft Trash"

[npcs]
rank_overseer = 211121
lowly_moleherd = 210818
royal_wicklighter = 210812
kobold_taskworker = 212383
wandering_candle = 208450
sootsnout = 212412
torchsnarl = 212411
skittering_darkness = 208457
shuffling_horror = 208456
corridor_creeper = 210539
creaky_mine_cart = 212129
