module_name = "Darkheart Thicket Trash"

[npcs]
mindshattered_screecher = 95769
dreadsoul_ruiner = 95771
dreadsoul_poisoner = 101679
crazed_razorbeak = 95766
festerhide_grizzly = 95779
vilethorn_blossom = 99360
rotheart_dryad = 99358
rotheart_keeper = 99359
nightmare_dweller = 101991
bloodtainted_fury = 113398
taintheart_summoner = 99366
dreadfire_imp = 100527
tormented_bloodseeker = 100526
