module_name = "Temple of the Jade Serpent Trash"

[npcs]
corrupt_living_water = 59873
fallen_waterspeaker = 200126
haunting_sha = 59555
the_talking_fish = 59546
the_songbird_queen = 59553
the_crybaby_hozen = 59552
the_nodding_tiger = 59544
the_golden_beetle = 59545
sha_touched_guardian = 200131
depraved_mistweaver = 200137
shambling_infester = 200387
minion_of_doubt = 57109
