module_name = "Halls of Infusion Trash"

[npcs]
primalist_ravager = 190348
primalist_geomancer = 190345
containment_apparatus = 190342
refti_defender = 190340
dazzling_dragonfly = 190362
curious_swoglet = 190366
primalist_shocktrooper = 199037
flamecaller_aymi = 190368
squallbringer_cyraz = 190370
primalist_earthshaker = 190371
primalist_galesinger = 190373
primalist_icecaller = 190377
gusting_protodragon = 190401
glacial_protodragon = 190403
subterranean_protodragon = 190404
aqua_rager = 190407
infuser_sariya = 190405
