module_name = "Ruby Life Pools Trash"

[npcs]
primal_juggernaut = 188244
flashfrost_earthshaper = 187969
flashfrost_chillweaver = 188067
defier_draghar = 187897
primalist_flamedancer = 190206
blazebound_destroyer = 190034
primalist_shockcaster = 195119
thunderhead = 197698
flamegullet = 197697
tempest_channeler = 198047
flame_channeler = 197985
high_channeler_ryvati = 197535
