module_name = "The Nokhud Offensive Trash"

[npcs]
nokhud_plainstomper = 191847
nokhud_hornsounder = 192796
nokhud_beastmaster = 192794
nokhud_longbow = 192789
primal_stormshield = 194896
primalist_stormspeaker = 194894
stormsurge_totem = 194897
primalist_thunderbeast = 195696
desecrated_ohuna = 195876
ukhel_deathspeaker = 195851
risen_mystic = 195877
ukhel_beastcaller = 195878
soulharvester_galtmaa = 195927
nokhud_defender = 199717
nokhud_thunderfist = 193373
balara = 193457
batak = 193462
