name: ci

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  code-check:
    name: code-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, win-msvc]
        include:
        - build: linux
          os: ubuntu-latest
        - build: macos
          os: macos-latest
        - build: win-msvc
          os: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        persist-credentials: false

    - name: Install Rust
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        toolchain: stable

    - name: Run cargo check
      run: cargo check

  code-style:
    name: code-style
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        persist-credentials: false

    - name: Install Rust
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        toolchain: 1.87.0
        components: rustfmt, clippy

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check clippy lints
      run: cargo clippy -- -D warnings
