# Based on https://github.com/BurntSushi/ripgrep/blob/ffd4c9ccba0ffc74270a8d3ae75f11a7ba7a1a64/.github/workflows/release.yml

name: release
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      version: ${{ env.VERSION }}
    steps:
      - name: Get the release version from the tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" | tee -a $GITHUB_ENV

      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}

  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos-aarch64, macos-x86_64, win-msvc, win32-msvc]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
        - build: macos-aarch64
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
        - build: macos-x86_64
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-latest
          rust: stable
          target: x86_64-pc-windows-msvc
        - build: win32-msvc
          os: windows-latest
          rust: stable
          target: i686-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
        target: ${{ matrix.target }}

    - name: Build release binaries
      run: cargo build --verbose --release --target ${{ matrix.target }}

    - name: Build archive
      shell: bash
      run: |
        OUTPUT_DIR="bw_locale_generator-${{ needs.create-release.outputs.version }}-${{ matrix.target }}"
        mkdir -p "$OUTPUT_DIR"

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp "target/${{ matrix.target }}/release/generate_toml_from_dir.exe" "$OUTPUT_DIR/"
          cp "target/${{ matrix.target }}/release/generate_toml_from_one.exe" "$OUTPUT_DIR/"
          cp "target/${{ matrix.target }}/release/localize_npc_names.exe" "$OUTPUT_DIR/"
          ASSET="$OUTPUT_DIR.zip"
          7z a "$ASSET" "$OUTPUT_DIR"
          echo "ASSET=$ASSET" | tee -a $GITHUB_ENV
        else
          cp "target/${{ matrix.target }}/release/generate_toml_from_dir" "$OUTPUT_DIR/"
          cp "target/${{ matrix.target }}/release/generate_toml_from_one" "$OUTPUT_DIR/"
          cp "target/${{ matrix.target }}/release/localize_npc_names" "$OUTPUT_DIR/"
          ASSET="$OUTPUT_DIR.tar.gz"
          tar czf "$ASSET" "$OUTPUT_DIR"
          echo "ASSET=$ASSET" | tee -a $GITHUB_ENV
        fi

    - name: Upload release archive
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{ env.ASSET }}
        asset_name: ${{ env.ASSET }}
        asset_content_type: application/octet-stream
